version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo "pre_build"
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - echo "build"
    - echo Build started on `date`
    - mvn install
    - mvn compile
    - mvn package
  post_build:
    commands:
    - echo "post_build"
    - echo Build completed on `date`
    - mv target/*.jar authservice-app.jar
    - dir
  artifacts:
    files:
    - authservice-app.jar
